#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("s_axi_config_AWVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_config_AWREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_config_AWADDR", 10, hls_in, -1, "", "", 1),
	Port_Property("s_axi_config_WVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_config_WREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_config_WDATA", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_config_WSTRB", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_config_ARVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_config_ARREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_config_ARADDR", 10, hls_in, -1, "", "", 1),
	Port_Property("s_axi_config_RVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_config_RREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_config_RDATA", 32, hls_out, -1, "", "", 1),
	Port_Property("s_axi_config_RRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("s_axi_config_BVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_config_BREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_config_BRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("interrupt", 1, hls_out, -1, "", "", 1),
	Port_Property("input_stream_V_TDATA", 32, hls_in, 6, "axis", "in_data", 1),
	Port_Property("output_stream_TDATA", 32, hls_out, 7, "axis", "out_data", 1),
	Port_Property("output_stream_TKEEP", 4, hls_out, 8, "axis", "out_data", 1),
	Port_Property("output_stream_TSTRB", 4, hls_out, 9, "axis", "out_data", 1),
	Port_Property("output_stream_TLAST", 1, hls_out, 10, "axis", "out_data", 1),
	Port_Property("input_stream_V_TVALID", 1, hls_in, 6, "axis", "in_vld", 1),
	Port_Property("input_stream_V_TREADY", 1, hls_out, 6, "axis", "in_acc", 1),
	Port_Property("output_stream_TVALID", 1, hls_out, 10, "axis", "out_vld", 1),
	Port_Property("output_stream_TREADY", 1, hls_in, 10, "axis", "out_acc", 1),
};
const char* HLS_Design_Meta::dut_name = "Filter2DKernel";
