// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Filter2DKernel_Filter2DKernel_entry4 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        bias_dout,
        bias_empty_n,
        bias_read,
        width_dout,
        width_empty_n,
        width_read,
        height_dout,
        height_empty_n,
        height_read,
        bias_out_din,
        bias_out_full_n,
        bias_out_write,
        width_out_din,
        width_out_full_n,
        width_out_write,
        width_out1_din,
        width_out1_full_n,
        width_out1_write,
        height_out_din,
        height_out_full_n,
        height_out_write,
        height_out2_din,
        height_out2_full_n,
        height_out2_write
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [15:0] bias_dout;
input   bias_empty_n;
output   bias_read;
input  [15:0] width_dout;
input   width_empty_n;
output   width_read;
input  [15:0] height_dout;
input   height_empty_n;
output   height_read;
output  [15:0] bias_out_din;
input   bias_out_full_n;
output   bias_out_write;
output  [15:0] width_out_din;
input   width_out_full_n;
output   width_out_write;
output  [15:0] width_out1_din;
input   width_out1_full_n;
output   width_out1_write;
output  [15:0] height_out_din;
input   height_out_full_n;
output   height_out_write;
output  [15:0] height_out2_din;
input   height_out2_full_n;
output   height_out2_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg bias_read;
reg width_read;
reg height_read;
reg bias_out_write;
reg width_out_write;
reg width_out1_write;
reg height_out_write;
reg height_out2_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    bias_blk_n;
reg    width_blk_n;
reg    height_blk_n;
reg    bias_out_blk_n;
reg    width_out_blk_n;
reg    width_out1_blk_n;
reg    height_out_blk_n;
reg    height_out2_blk_n;
reg    ap_block_state1;
reg   [0:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((real_start == 1'b0) | (height_out2_full_n == 1'b0) | (height_out_full_n == 1'b0) | (width_out1_full_n == 1'b0) | (width_out_full_n == 1'b0) | (bias_out_full_n == 1'b0) | (height_empty_n == 1'b0) | (width_empty_n == 1'b0) | (bias_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (height_out2_full_n == 1'b0) | (height_out_full_n == 1'b0) | (width_out1_full_n == 1'b0) | (width_out_full_n == 1'b0) | (bias_out_full_n == 1'b0) | (height_empty_n == 1'b0) | (width_empty_n == 1'b0) | (bias_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        bias_blk_n = bias_empty_n;
    end else begin
        bias_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        bias_out_blk_n = bias_out_full_n;
    end else begin
        bias_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (height_out2_full_n == 1'b0) | (height_out_full_n == 1'b0) | (width_out1_full_n == 1'b0) | (width_out_full_n == 1'b0) | (bias_out_full_n == 1'b0) | (height_empty_n == 1'b0) | (width_empty_n == 1'b0) | (bias_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        bias_out_write = 1'b1;
    end else begin
        bias_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (height_out2_full_n == 1'b0) | (height_out_full_n == 1'b0) | (width_out1_full_n == 1'b0) | (width_out_full_n == 1'b0) | (bias_out_full_n == 1'b0) | (height_empty_n == 1'b0) | (width_empty_n == 1'b0) | (bias_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        bias_read = 1'b1;
    end else begin
        bias_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_blk_n = height_empty_n;
    end else begin
        height_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_out2_blk_n = height_out2_full_n;
    end else begin
        height_out2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (height_out2_full_n == 1'b0) | (height_out_full_n == 1'b0) | (width_out1_full_n == 1'b0) | (width_out_full_n == 1'b0) | (bias_out_full_n == 1'b0) | (height_empty_n == 1'b0) | (width_empty_n == 1'b0) | (bias_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_out2_write = 1'b1;
    end else begin
        height_out2_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_out_blk_n = height_out_full_n;
    end else begin
        height_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (height_out2_full_n == 1'b0) | (height_out_full_n == 1'b0) | (width_out1_full_n == 1'b0) | (width_out_full_n == 1'b0) | (bias_out_full_n == 1'b0) | (height_empty_n == 1'b0) | (width_empty_n == 1'b0) | (bias_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_out_write = 1'b1;
    end else begin
        height_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (height_out2_full_n == 1'b0) | (height_out_full_n == 1'b0) | (width_out1_full_n == 1'b0) | (width_out_full_n == 1'b0) | (bias_out_full_n == 1'b0) | (height_empty_n == 1'b0) | (width_empty_n == 1'b0) | (bias_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_read = 1'b1;
    end else begin
        height_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (height_out2_full_n == 1'b0) | (height_out_full_n == 1'b0) | (width_out1_full_n == 1'b0) | (width_out_full_n == 1'b0) | (bias_out_full_n == 1'b0) | (height_empty_n == 1'b0) | (width_empty_n == 1'b0) | (bias_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_blk_n = width_empty_n;
    end else begin
        width_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_out1_blk_n = width_out1_full_n;
    end else begin
        width_out1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (height_out2_full_n == 1'b0) | (height_out_full_n == 1'b0) | (width_out1_full_n == 1'b0) | (width_out_full_n == 1'b0) | (bias_out_full_n == 1'b0) | (height_empty_n == 1'b0) | (width_empty_n == 1'b0) | (bias_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_out1_write = 1'b1;
    end else begin
        width_out1_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_out_blk_n = width_out_full_n;
    end else begin
        width_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (height_out2_full_n == 1'b0) | (height_out_full_n == 1'b0) | (width_out1_full_n == 1'b0) | (width_out_full_n == 1'b0) | (bias_out_full_n == 1'b0) | (height_empty_n == 1'b0) | (width_empty_n == 1'b0) | (bias_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_out_write = 1'b1;
    end else begin
        width_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (height_out2_full_n == 1'b0) | (height_out_full_n == 1'b0) | (width_out1_full_n == 1'b0) | (width_out_full_n == 1'b0) | (bias_out_full_n == 1'b0) | (height_empty_n == 1'b0) | (width_empty_n == 1'b0) | (bias_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_read = 1'b1;
    end else begin
        width_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (height_out2_full_n == 1'b0) | (height_out_full_n == 1'b0) | (width_out1_full_n == 1'b0) | (width_out_full_n == 1'b0) | (bias_out_full_n == 1'b0) | (height_empty_n == 1'b0) | (width_empty_n == 1'b0) | (bias_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign bias_out_din = bias_dout;

assign height_out2_din = height_dout;

assign height_out_din = height_dout;

assign start_out = real_start;

assign width_out1_din = width_dout;

assign width_out_din = width_dout;

endmodule //Filter2DKernel_Filter2DKernel_entry4
